ALTER TABLE coupons
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE
    USING created_at AT TIME ZONE 'UTC',
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE coupon_usages
    ALTER COLUMN used_at TYPE TIMESTAMP WITH TIME ZONE
    USING used_at AT TIME ZONE 'UTC',
    ALTER COLUMN used_at SET DEFAULT CURRENT_TIMESTAMP;